import React, { Fragment } from 'react';
import AboutUs from '../components/advert/aboutus';
import './about.css'
import about from "../assets/photojpg.png"

import BrandLink from './../components/BrandLink';
import FactNumber from './../components/FactNumber';

const About = () => {
    return (
        <Fragment>
            <AboutUs/>
            <div className="infoPage">
<img style={{width:"600px"}} src={about} alt="" />
<div className="infoElegance">
<h3>Elegance what you deserves</h3>
<div className="mx-auto w-2/3">
<p className="mb-4">
Fabulous is the leading premium beauty platform in Europe. Offering more than 130,000 beauty and lifestyle products in online shops, the beauty marketplace and more than 2,000 stores, Fabulous inspires customers to live their own kind of beauty by a previously unparalleled assortment.
                    </p>
<p>
The continued expansion of the fast-growing e‑commerce business is the focus of the
<span className="font-krona"> #forwardbeauty</span>. DigitalFirst strategy programme. In fiscal year 2019/2020, Welly generated sales of 3.2 billion euros in the areas of perfumery, decorative cosmetics, skin and hair care as well as nutritional supplements and accessories.
 <span className="font-krona"> #letsdobeautiful</span>
                    </p>
                </div>

            <div className="iconsInfo">
 <FactNumber
 icon={'people'}
number="20,000"
title="Beauty Experts"
description="strive to make their customers more beautiful and thus happier"/>
<FactNumber
icon={'revenue'}
number="3.2"
 title="Billion Euros"
 description="revenue was generated by Douglas in the 2019/20 financial year"
                    />
<FactNumber
icon={'shop'}
number="130,000"
title="Care Products"
description="because we care about you in online shops, and in stores" />
            </div>
            </div>
            </div>
<section className="contact">
<div className="">
<h2>Leave us a message</h2>
<div className="flexMessage">
<p>-Good for nature, Good for you-</p>
</div>
<div className="form">
 <form id="myForm">
<div className="form_name">
 <input type="text" name="firstName" id="firstName" placeholder="Name" required />
<input type="text" name="lastName" id="lastName" placeholder="Surname" />
</div>
<input type="email" name="email" id="email" placeholder="Tour email" required />
<textarea name="message" id="message" cols="10" rows="5" placeholder="Message" required></textarea>
<input type="submit" value="Send message" />
                    </form>
                </div>
            </div>
        </section>
        </Fragment>
    );
};

export default About;
